const INT_SCALE = 7;
const INT_SCALE_IVS = 1 / INT_SCALE;
const INT_OFFSET = 500;

const BLEND_DIST_FACTOR = 100;
const MAX_OBJECTS_COUNT = 64;
const DATA_TEXTURE_SIZE = MAX_OBJECTS_COUNT;
const DATA_TEXTURE_SIZE_IVS = 1 / DATA_TEXTURE_SIZE;

export {
    INT_SCALE,
    INT_OFFSET,
    INT_SCALE_IVS,
    BLEND_DIST_FACTOR,
    MAX_OBJECTS_COUNT,
    DATA_TEXTURE_SIZE,
    DATA_TEXTURE_SIZE_IVS
};