const INT_SCALE = 7;
const INT_SCALE_IVS = 1 / INT_SCALE;
const INT_OFFSET = 500;

const DATA_TEXTURE_SIZE = 128;
const DATA_TEXTURE_SIZE_IVS = 1 / DATA_TEXTURE_SIZE;

export {
    INT_SCALE,
    INT_OFFSET,
    INT_SCALE_IVS,
    DATA_TEXTURE_SIZE,
    DATA_TEXTURE_SIZE_IVS
};