const INT_SCALE = 5;
const INT_SCALE_IVS = 1 / INT_SCALE;

const DATA_TEXTURE_SIZE = 128;
const DATA_TEXTURE_SIZE_IVS = 1 / DATA_TEXTURE_SIZE;

export {
    INT_SCALE,
    INT_SCALE_IVS,
    DATA_TEXTURE_SIZE,
    DATA_TEXTURE_SIZE_IVS
};